# Generated by Django 4.0.3 on 2022-04-09 21:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=20)),
                ('middle_name', models.CharField(blank=True, help_text='Middle Name', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Last Name (surname)', max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Mobile Phone Number', max_length=11, region=None)),
                ('email', models.EmailField(help_text='Official Email(e.g. j.doe@edostate.gov.ng)', max_length=254)),
                ('birth_month', models.IntegerField(help_text='Month of birth', max_length=3)),
                ('birth_day', models.IntegerField(help_text='Birth day', max_length=3)),
            ],
        ),
    ]
