# Generated by Django 4.0.3 on 2022-04-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_staffdetails_birthday_today_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdetails',
            options={'ordering': ['first_name', 'middle_name', 'last_name', 'email', 'phone_number']},
        ),
    ]
