# Generated by Django 4.0.3 on 2022-04-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0003_alter_staffdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdetails',
            options={'ordering': ['first_name', 'middle_name']},
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='birthday_today',
        ),
    ]
