# Generated by Django 3.2.13 on 2022-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_alter_staffdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffdetails',
            options={},
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
    ]
