# Generated by Django 3.2.13 on 2022-06-04 19:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0005_auto_20220604_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='birth_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Birth month of staff', verbose_name='Birth Month'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(help_text='Official Email(e.g. j.doe@edostate.gov.ng)', max_length=254, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
