# Generated by Django 3.2.13 on 2022-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0006_auto_20220604_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='birth_month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, verbose_name='Birth Month'),
        ),
    ]
