# Generated by Django 3.2.13 on 2022-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0007_alter_staffdetails_birth_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='staffimages', verbose_name="Staff's Image"),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Official Email'),
        ),
    ]
