# Generated by Django 3.2.13 on 2022-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0008_auto_20220607_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(blank=True, default='staffimages/default.jpg', null=True, upload_to='staffimages', verbose_name="Staff's Image"),
        ),
        migrations.AlterModelTable(
            name='staffdetails',
            table='sendmail_staffdetails',
        ),
    ]
