# Generated by Django 4.0.5 on 2022-06-09 20:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0010_staffdetails_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0801 234 5678', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Position'),
        ),
    ]
