# Generated by Django 4.0.5 on 2022-06-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0011_alter_staffdetails_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffdetails',
            table=None,
        ),
    ]
