# Generated by Django 4.0.5 on 2022-06-10 10:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0012_alter_staffdetails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0801 234 5678', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterModelTable(
            name='staffdetails',
            table='sendmail_staffdetails',
        ),
    ]
