# Generated by Django 4.0.5 on 2022-06-12 23:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0012_alter_staffdetails_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='position',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='cadre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cadre'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='gender',
            field=models.CharField(default='Female', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(default='1', verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='step',
            field=models.IntegerField(blank=True, default='2', null=True, verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0800 000 0000', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staffimage',
            field=models.ImageField(blank=True, default='staffimages/default.jpg', null=True, upload_to='staffimages', verbose_name='Profile Picture'),
        ),
        migrations.AlterModelTable(
            name='staffdetails',
            table='sendmail_staffdetails',
        ),
    ]
