# Generated by Django 4.0.5 on 2022-06-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0016_alter_staffdetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='gender',
        ),
    ]
