# Generated by Django 4.0.5 on 2022-06-16 09:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0018_staffdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='birth_day',
            field=models.IntegerField(default=1, verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='cadre',
            field=models.CharField(default='Admin (default)', max_length=50, verbose_name='Cadre'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(default='email@edostate.gov.ng (default)', max_length=254, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='first_name',
            field=models.CharField(default='John (default)', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='last_name',
            field=models.CharField(default='Doe (default)', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(default='staffimages/default.jpg', upload_to='staffimages', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='step',
            field=models.IntegerField(default=2, verbose_name='Step'),
        ),
    ]
