# Generated by Django 4.0.5 on 2022-06-19 19:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0019_alter_staffdetails_birth_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='Departmet',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='birth_day',
            field=models.IntegerField(verbose_name='Birth Day'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='cadre',
            field=models.CharField(max_length=50, verbose_name='Cadre'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Official Email'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0800 000 0000', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='step',
            field=models.IntegerField(verbose_name='Step'),
        ),
    ]
