# Generated by Django 4.0.5 on 2022-06-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0020_staffdetails_departmet_alter_staffdetails_birth_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='Departmet',
            new_name='department',
        ),
    ]
