# Generated by Django 4.0.5 on 2022-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0021_rename_departmet_staffdetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(default='Admin Dept (default)', max_length=100, verbose_name='Department'),
        ),
    ]
