# Generated by Django 4.0.6 on 2022-07-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0022_alter_staffdetails_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='first_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Date of First Appointment'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(verbose_name='Grade Level'),
        ),
    ]
