# Generated by Django 4.0.6 on 2022-07-11 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0023_staffdetails_first_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='first_appointment',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of First Appointment'),
        ),
    ]
