# Generated by Django 4.0.6 on 2022-07-11 10:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0024_alter_staffdetails_first_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08012345678', max_length=11, region=None, verbose_name='Phone Number'),
        ),
    ]
