# Generated by Django 4.0.6 on 2022-07-12 10:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0025_alter_staffdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08012345678', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(default='staffimages/default-female.jpg', upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
