# Generated by Django 4.0.6 on 2022-07-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0026_alter_staffdetails_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
