# Generated by Django 4.0.6 on 2022-07-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffdetails',
            table='birthday_staffdetails',
        ),
    ]
