# Generated by Django 4.0.6 on 2022-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_alter_staffdetails_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='remove_image',
            field=models.BooleanField(null=True, verbose_name='Remove Picture'),
        ),
    ]
