# Generated by Django 4.0.6 on 2022-07-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_alter_staffdetails_remove_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetails',
            old_name='remove_image',
            new_name='delete_image',
        ),
    ]
