# Generated by Django 4.0.6 on 2022-07-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_alter_staffdetails_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(default='staffimages/default.png', upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
