# Generated by Django 4.0.6 on 2022-07-22 08:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0009_alter_staffdetails_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='gender',
            field=models.CharField(choices=[(None, 'Select your gender'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], default=2, max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(blank=True, upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
