# Generated by Django 4.0.6 on 2022-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0010_alter_staffdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
