# Generated by Django 4.0.6 on 2022-07-24 17:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0012_alter_staffdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='09123456789', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
