# Generated by Django 4.0.6 on 2022-07-23 12:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0012_alter_staffdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='09000000000', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
