# Generated by Django 4.0.6 on 2022-07-25 12:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0013_alter_staffdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(default=6, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='09123456789', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='step',
            field=models.IntegerField(default=2, verbose_name='Step'),
        ),
    ]
