# Generated by Django 4.0.6 on 2022-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0013_alter_staffdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2, verbose_name='Gender'),
        ),
    ]
