# Generated by Django 4.0.6 on 2022-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0014_alter_staffdetails_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('Administration and Supply', 'Administration and Supply'), ('Accounts', 'Accounts'), ('Business Premises', 'Business Premises'), ('Cooperatives', 'Cooperatives'), ('Industry', 'Industry'), ('MSMEs', 'MSMEs'), ('Policy Formulation', 'Policy Formulation'), ('Planning, Research and Statistics', 'Planning, Research and Statistics'), ('Trade Promotions and Marketing', 'Trade Promotions and Marketing')], default='Administration and Supply', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staff_image',
            field=models.ImageField(null=True, upload_to='staffimages', verbose_name='Profile Picture'),
        ),
    ]
