# Generated by Django 4.0.6 on 2022-07-24 16:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0014_alter_staffdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31, null=True, verbose_name='Phone Number'),
        ),
    ]
