# Generated by Django 4.0.6 on 2022-08-03 21:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0017_alter_staffdetails_cadre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='cadre',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Account Officer', 'Account Officer'), ('Executive', 'Executive'), ('Chief Secretary Assistant', 'Chief Secretary Assistant'), ('Commercial Officer', 'Commercial Officer'), ('Cooperative Officer', 'Cooperative Officer'), ('Industrial Promotion Officer', 'Industrial Promotion Officer'), ('Motor Driver/Mechanic', 'Motor Driver/Mechanic'), ('Messenger', 'Messenger'), ('Procurement', 'Procurement'), ('Program Analyst', 'Program Analyst'), ('Statistician', 'Statistician'), ('Stores Officer', 'Stores Officer'), ('Trade Officer', 'Trade Officer'), ('Watchman', 'Watchman')], default='Administrative', max_length=100, verbose_name='Cadre'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Business Premises', 'Business Premises'), ('Cooperatives', 'Cooperatives'), ('Human Resource', 'Human Resource'), ('Industry', 'Industry'), ('MSMEs', 'MSMEs'), ('Policy Formulation', 'Policy Formulation'), ('Planning, Research and Statistics', 'Planning, Research and Statistics'), ('Trade Promotions and Marketing', 'Trade Promotions and Marketing')], default='Administration and Supply', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='level',
            field=models.IntegerField(verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='step',
            field=models.IntegerField(verbose_name='Step'),
        ),
    ]
