# Generated by Django 4.0.6 on 2022-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0018_alter_staffdetails_cadre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='cadre',
            field=models.CharField(choices=[('Administrative', 'Administrative'), ('Account Officer', 'Account Officer'), ('Executive', 'Executive'), ('Chief Secretary Assistant', 'Chief Secretary Assistant'), ('Commercial Officer', 'Commercial Officer'), ('Confidential Secretary', 'Confidential Secretary'), ('Cooperative Officer', 'Cooperative Officer'), ('Driver/Mechanic', 'Driver/Mechanic'), ('Industrial Promotion Officer', 'Industrial Promotion Officer'), ('Messenger', 'Messenger'), ('Procurement', 'Procurement'), ('Program Analyst', 'Program Analyst'), ('Statistician', 'Statistician'), ('Stores Officer', 'Stores Officer'), ('Trade Officer', 'Trade Officer'), ('Watchman', 'Watchman')], default='Administrative', max_length=100, verbose_name='Cadre'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Business Premises', 'Business Premises'), ('Cooperatives', 'Cooperatives'), ('Human Resource', 'Human Resource'), ('Industry', 'Industry'), ('MSMEs', 'MSMEs'), ('Office of the Permanent Secretary', 'Office of the Permanent Secretary'), ('Office of the Honourable Commissioner', 'Office of the Honourable Commissioner'), ('Policy Formulation', 'Policy Formulation'), ('Planning, Research and Statistics', 'Planning, Research and Statistics'), ('Trade Promotions and Marketing', 'Trade Promotions and Marketing')], default='Administration and Supply', max_length=100, verbose_name='Department'),
        ),
    ]
