# Generated by Django 5.0.4 on 2024-04-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("birthday", "0020_alter_staffdetails_cadre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="staffDetails",
        ),
    ]
