# Generated by Django 5.0.4 on 2024-04-09 01:59

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="staffDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="Last Name"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number"
                    ),
                ),
                (
                    "official_email",
                    models.EmailField(max_length=254, verbose_name="Official Email"),
                ),
                (
                    "cadre",
                    models.CharField(
                        choices=[
                            ("Administrative", "Administrative"),
                            ("Account Officer", "Account Officer"),
                            ("Executive", "Executive"),
                            ("Chief Secretary Assistant", "Chief Secretary Assistant"),
                            ("Commercial Officer", "Commercial Officer"),
                            ("Confidential Secretary", "Confidential Secretary"),
                            ("Cooperative Officer", "Cooperative Officer"),
                            ("Driver/Mechanic", "Driver/Mechanic"),
                            (
                                "Industrial Promotion Officer",
                                "Industrial Promotion Officer",
                            ),
                            ("Messenger", "Messenger"),
                            ("Permanent Secretary", "Permanent Secretary"),
                            ("Procurement", "Procurement"),
                            ("Program Analyst", "Program Analyst"),
                            ("Statistician", "Statistician"),
                            ("Stores Officer", "Stores Officer"),
                            ("Trade Officer", "Trade Officer"),
                            ("Watchman", "Watchman"),
                        ],
                        default="Administrative",
                        max_length=100,
                        verbose_name="Cadre",
                    ),
                ),
                (
                    "first_appointment",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Date of First Appointment",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Accounts", "Accounts"),
                            ("Business Premises", "Business Premises"),
                            ("Cooperatives", "Cooperatives"),
                            ("Human Resources", "Human Resources"),
                            ("Industry", "Industry"),
                            ("MSMEs", "MSMEs"),
                            (
                                "Office of the Permanent Secretary",
                                "Office of the Permanent Secretary",
                            ),
                            (
                                "Office of the Honourable Commissioner",
                                "Office of the Honourable Commissioner",
                            ),
                            ("Policy Formulation", "Policy Formulation"),
                            (
                                "Planning, Research and Statistics",
                                "Planning, Research and Statistics",
                            ),
                            (
                                "Trade Promotions and Marketing",
                                "Trade Promotions and Marketing",
                            ),
                        ],
                        default="Administration and Supply",
                        max_length=100,
                        verbose_name="Department",
                    ),
                ),
                ("level", models.IntegerField(verbose_name="Grade Level")),
                ("step", models.IntegerField(verbose_name="Step")),
                (
                    "staff_image",
                    models.ImageField(
                        default="staffimages/default.png",
                        upload_to="staffimages",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "delete_image",
                    models.BooleanField(
                        default=0, verbose_name="Delete Profile Picture"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (2, "Female")],
                        default=2,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "birth_month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=1,
                        verbose_name="Birth Month",
                    ),
                ),
                ("birth_day", models.IntegerField(verbose_name="Birth Day")),
                (
                    "date_of_birth",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date of Birth"
                    ),
                ),
            ],
            options={
                "db_table": "birthday_staffdetails",
            },
        ),
    ]
