# Generated by Django 5.0.4 on 2024-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapp", "0002_alter_staffdetails_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffdetails",
            name="birth_day",
        ),
        migrations.RemoveField(
            model_name="staffdetails",
            name="birth_month",
        ),
        migrations.RemoveField(
            model_name="staffdetails",
            name="level",
        ),
        migrations.AddField(
            model_name="staffdetails",
            name="grade_level",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                ],
                default=1,
                verbose_name="Grade Level",
            ),
        ),
    ]
