# Generated by Django 5.0.4 on 2024-04-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffapp", "0003_remove_staffdetails_birth_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdetails",
            name="step",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1, verbose_name="Step"
            ),
        ),
    ]
